title: Practica 2 - Instalación y configuración de Visual Studio Code
author: Eduardo Brito 
email: eebritosa@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Informe de la Practica 2 de la asignatura de Desarrollo de Sistemas Informaticos
# social links
github_username:  eduardobritosan # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-slate